language: php

php: 7.2

branches:
    only:
        - master

cache:
    directories:
    - $HOME/.composer/cache

install:
    - composer install
    - npm install

before_script:
    - phpenv config-rm xdebug.ini || return 0
    - composer check

script:
    - vendor/bin/jigsaw build production

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: build_production

notifications:
    email:
        on_success: always
        on_failure: always
